### ISSUE TITLE
Consider non-docker-based workflow?

### ISSUE THREAD

**Issue by rdhar** [GlueOps/github-actions-opentofu-continuous-delivery#31]
Really neat workflow, bringing together a number of pieces under "one roof".

During on private/self-hosted runners, often run into Docker pull rate-limiting since the (underlying) Actions are docker-based.

Wonder if you happen to have considered [DevSecTop/TF-via-PR](https://github.com/DevSecTop/TF-via-PR)? Note, I'm the maintainer of the project so I'm on the lookout for similar tooling and their feature offering.

**Comment by venkatamutyala** [comment]
@rdhar Apologies for the late reply. I actually just came across your project recently on reddit! I was googling last night and just trying to figure out what we can do to improve our existing actions which is where i stumbled across a post on reddit that mentioned your project. Just sent you a linkedin request. Let's do a call sometime and see if we can collaborate to consolidate projects.

RE: rate limits, I can see that being an issue. I don't have a solution for you beyond trying to loging to docker hub before running the action

**Comment by rdhar** [comment]
Hi @venkatamutyala, no worries at all. Good shout on the DockerHub login workaround—that'll certainly bump up the rate thresholds a fair bit.

I'm always pleasantly surprised by how folks find their way to niche GitHub Actions, but Reddit is by far the most popular source yet! I think it might be worth considering making a post or two in /r/terraform, especially given the imminent major-version release bump of TF-via-PR within the next few days.

I think we found each other on LinkedIn _and_ SweetOps Slack!
